# Generated by Django 3.0.2 on 2020-01-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name_plural': 'Pontos Turisticos'},
        ),
    ]
