# Generated by Django 3.0.2 on 2020-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0007_auto_20200122_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='aprovado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
