# Generated by Django 3.0.2 on 2020-01-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('horario_func', models.TextField()),
                ('idade_minima', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Atrações',
            },
        ),
    ]
